/** @type {import("stylelint").Config} */
const bemWord = "[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*";

const config = {
  plugins: ["stylelint-order", "@stylistic/stylelint-plugin", "stylelint-selector-bem-pattern"],
  ignoreFiles: ["**/.next/**", "**/node_modules/**"],
  rules: {
    "plugin/selector-bem-pattern": {
      implicitComponents: ["app/**/*.module.css"],
      ignoreSelectors: [":root", "html", "body", "\\*"],
      componentSelectors: () => {
        const element = `(?:__${bemWord})?`;
        const modifier = `(?:(?:_|--)${bemWord}){0,2}`;
        return new RegExp(`^\\.${bemWord}${element}${modifier}$`);
      },
    },
    // rem — текст и ритм страницы; em — внутри кнопки/инпута; px — рамка, тень, иконка.
    // Правило только подсвечивает, --fix единицы не переписывает.
    "unit-allowed-list": ["px", "em", "rem", "%", "s", "ms", "deg", "fr", "vw", "vh", "dvh", "svh", "lvh"],
    "declaration-property-unit-allowed-list": {
      "font-size": ["rem"],
      "line-height": [],
      "letter-spacing": ["em"],
      "text-underline-offset": ["em"],
      "/^padding/": ["rem", "em"],
      "/^margin/": ["rem", "em", "vw"],
      "/^(row-|column-)?gap$/": ["rem", "em"],
      "/^border(-(top|right|bottom|left))?(-width)?$/": ["px"],
      "outline": ["px"],
      "outline-width": ["px"],
      "box-shadow": ["px"],
      "border-radius": ["rem", "%"],
      "/^(min-|max-)?(width|height)$/": ["rem", "em", "px", "%", "vh", "dvh", "svh", "lvh"],
      "/^(top|right|bottom|left|inset)$/": ["rem", "em", "%"],
    },
    "@stylistic/indentation": 4,
    "order/properties-order": [
      {
        groupName: "positioning",
        emptyLineBefore: "always",
        noEmptyLineBetween: true,
        properties: ["content", "position", "inset", "top", "right", "bottom", "left", "z-index"],
      },
      {
        groupName: "box",
        emptyLineBefore: "always",
        noEmptyLineBetween: true,
        properties: [
          "display",
          "flex",
          "flex-grow",
          "flex-shrink",
          "flex-basis",
          "flex-direction",
          "flex-wrap",
          "justify-content",
          "align-content",
          "align-items",
          "align-self",
          "order",
          "grid",
          "float",
          "clear",
          "box-sizing",
          "width",
          "min-width",
          "max-width",
          "height",
          "min-height",
          "max-height",
          "margin",
          "margin-top",
          "margin-right",
          "margin-bottom",
          "margin-left",
          "padding",
          "padding-top",
          "padding-right",
          "padding-bottom",
          "padding-left",
          "overflow",
          "overflow-x",
          "overflow-y",
          "list-style",
          "list-style-position",
          "list-style-type",
        ],
      },
      {
        groupName: "typography",
        emptyLineBefore: "always",
        noEmptyLineBetween: true,
        properties: [
          "font",
          "font-family",
          "font-style",
          "font-size",
          "line-height",
          "font-weight",
          "letter-spacing",
          "text-align",
          "white-space",
          "color",
          "text-transform",
          "text-decoration",
          "text-underline-offset",
        ],
      },
      {
        groupName: "visual",
        emptyLineBefore: "always",
        noEmptyLineBetween: true,
        properties: [
          "background",
          "background-color",
          "background-image",
          "border",
          "border-radius",
          "outline",
          "box-shadow",
          "opacity",
          "transform",
        ],
      },
      {
        groupName: "animation",
        emptyLineBefore: "always",
        noEmptyLineBetween: true,
        properties: ["transition", "animation"],
      },
    ],
  },
};

export default config;
