/** @type {import("stylelint").Config} */
const config = {
  plugins: ["stylelint-order", "@stylistic/stylelint-plugin"],
  ignoreFiles: ["**/.next/**", "**/node_modules/**"],
  rules: {
    "@stylistic/indentation": 4,
    "order/properties-order": [
      {
        groupName: "positioning",
        emptyLineBefore: "always",
        noEmptyLineBetween: true,
        properties: ["content", "position", "inset", "top", "right", "bottom", "left", "z-index"],
      },
      {
        groupName: "box",
        emptyLineBefore: "always",
        noEmptyLineBetween: true,
        properties: [
          "display",
          "flex",
          "flex-grow",
          "flex-shrink",
          "flex-basis",
          "flex-direction",
          "flex-wrap",
          "justify-content",
          "align-content",
          "align-items",
          "align-self",
          "order",
          "grid",
          "float",
          "clear",
          "box-sizing",
          "width",
          "min-width",
          "max-width",
          "height",
          "min-height",
          "max-height",
          "margin",
          "margin-top",
          "margin-right",
          "margin-bottom",
          "margin-left",
          "padding",
          "padding-top",
          "padding-right",
          "padding-bottom",
          "padding-left",
          "overflow",
          "overflow-x",
          "overflow-y",
          "list-style",
          "list-style-position",
          "list-style-type",
        ],
      },
      {
        groupName: "typography",
        emptyLineBefore: "always",
        noEmptyLineBetween: true,
        properties: [
          "font",
          "font-family",
          "font-style",
          "font-size",
          "line-height",
          "font-weight",
          "letter-spacing",
          "text-align",
          "white-space",
          "color",
          "text-transform",
          "text-decoration",
          "text-underline-offset",
        ],
      },
      {
        groupName: "visual",
        emptyLineBefore: "always",
        noEmptyLineBetween: true,
        properties: [
          "background",
          "background-color",
          "background-image",
          "border",
          "border-radius",
          "outline",
          "box-shadow",
          "opacity",
          "transform",
        ],
      },
      {
        groupName: "animation",
        emptyLineBefore: "always",
        noEmptyLineBetween: true,
        properties: ["transition", "animation"],
      },
    ],
  },
};

export default config;
